Repository Think-N-Kreate-Ltd/AGIS-Longevity-Tester-firmware, pull requests merged in 2023-09, with the labels that each got.

#5 add INA219 debug info and update readme
  README.md
  src/TESTER_INA219.cpp
Labels: documentation

#8 Feature/no ref/log pause state
  README.md
  include/TESTER_LOGGING.h
  include/Tester_Display.h
  include/Tester_common.h
  lib/AsyncElegantOTA/.gitattributes
  lib/AsyncElegantOTA/.github/FUNDING.yml
  lib/AsyncElegantOTA/.github/ISSUE_TEMPLATE/bug-report.md
  lib/AsyncElegantOTA/.github/scripts/dep-install.sh
  lib/AsyncElegantOTA/.github/workflows/ci.yml
  lib/AsyncElegantOTA/.gitignore
  lib/AsyncElegantOTA/.piopm
  lib/AsyncElegantOTA/LICENSE
  lib/AsyncElegantOTA/README.md
  lib/AsyncElegantOTA/examples/Async_Demo/Async_Demo.ino
  lib/AsyncElegantOTA/keywords.txt
  lib/AsyncElegantOTA/library.properties
  lib/AsyncElegantOTA/src/AsyncElegantOTA.h
  lib/AsyncElegantOTA/src/Hash.h
  lib/AsyncElegantOTA/src/elegantWebpage.h
  lib/AsyncElegantOTA/ui/README.md
  lib/TFT_Setups/240x320_TFT_setup.h
  lib/TFT_Setups/Free_Fonts.h
  lib/TFT_Setups/lv_conf.h
  src/TESTER_LOGGING.cpp
  src/Tester_Display.cpp
  src/UI/CMakeLists.txt
  src/UI/components/ui_comp_hook.c
  src/UI/filelist.txt
  src/UI/screens/ui_input.c
  src/UI/screens/ui_monitor.c
  src/UI/ui.c
  src/UI/ui.h
  src/UI/ui_events.h
  src/UI/ui_helpers.c
  src/UI/ui_helpers.h
  src/main.cpp
Labels: documentation, enhancement

#9 Experimental/see description/UI bugfix improvement
  README.md
  description.md
  src/Tester_Display.cpp
  src/main.cpp
Labels: bug, enhancement
